[project]
name = "mcp-polaris-ai-datainsight"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
polaris-ai-datainsight = "^0.1.1"
mcp = {extras = ["cli"], version = "^1.6.0"}
